### ISSUE TITLE
Help Wanted - Please Submit Examples for Your Common Scenarios!

### ISSUE THREAD

**Issue by bisdavid** [awsdocs/aws-javascript-developer-guide-v2#12]
Hey everyone! We're always on the lookout for good examples that illustrate "best practices" for performing common tasks using the AWS JavaScript SDK. We provide as many samples as we can when we first publish a guide, but only you know what you automate using the JavaScript SDK for on a daily basis. What common tasks have you automated with the AWS JavaScript SDK that others could learn from? Share your examples with us!

Submit a pull request as explained in these directions: https://github.com/awsdocs/aws-javascript-developer-guide-v2/blob/master/CONTRIBUTING.md

Thank you!
Dave Bishop

**Comment by Doug-AWS** [comment]
No responses == closing.
