### ISSUE TITLE
Users don't get contribution credit after their PR is merged

### ISSUE THREAD

**Issue by trivikr** [awsdocs/aws-javascript-developer-guide-v2#25]
Issue:
* Recently 4 of my PRs were merged in ([link](https://github.com/awsdocs/aws-javascript-developer-guide-v2/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Atrivikr+is%3Aclosed))
* However, the contributions are not linked to my GitHub account ([contributors graph](https://github.com/awsdocs/aws-javascript-developer-guide-v2/graphs/contributors), [commit](https://github.com/awsdocs/aws-javascript-developer-guide-v2/commit/7f534befd0a5c1e74dbbaa90c081dccef2a8114f))

Fix:
When commits are merged in the repo, link the commits with contributor who created the PR. This will encourage more people to contribute.

**Comment by ghost** [comment]
Thanks for the bringing this to our attention. We'll try to be more mindful of this in the future. 

Paul
AWS Documentation
