### ISSUE TITLE
JSON for CORS has an error (and photos don't list)

### ISSUE THREAD

**Issue by tensigh** [awsdocs/aws-javascript-developer-guide-v2#45]
Two issues:

The JSON for CORS has an error. 

Instead of         

"AllowedMethods": [
            "HEAD",
            "GET",
}

You have to remove the second comma:

        "AllowedMethods": [
            "HEAD",
            "GET"
}

Also, I can't get my photos to list. They just say "There are no photos in this album"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
