### ISSUE TITLE
Objects being created, not folders

### ISSUE THREAD

**Issue by mpltr** [awsdocs/aws-javascript-developer-guide-v2#47]
Hi, this example feels pretty misleading. When you create and album you're just creating an empty object, not a folder. When you add an image to that folder it then creates the folder with that image in it. This means if you don't immediately add an image to the folder when created and reload the page, it isn't visible on the list folder screen, nor is there a folder in the s3 bucket.

By adding a forward slash to the end of the album name, it looks like it does create the folder. Is this a typo or just written on a previous version of the sdk?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
