### ISSUE TITLE
This documentation needs updating.

### ISSUE THREAD

**Issue by danielcranney** [awsdocs/aws-javascript-developer-guide-v2#54]
This document is extremely confusing, as it suggests it is essential to title Environmental Variables with "AWS" as a prefix, and yet this is specifically a reserved prefix when using Amazon Amplify.

It does not make sense to recommend a name that is specifically banned within Amazon's own ecosystem.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
